service: passwordgenerator

provider:
  name: aws
  runtime: nodejs12.x

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: password
          method: post
          cors: true